### ISSUE TITLE
Cannot generate grid_world data with script_make_data.m

### ISSUE THREAD

**Issue by zhongwen** [avivt/VIN#1]
I tried to produce the grid_world data wth the script of `script_make_data.m`. However, I obtained 

```no obstacles added, or problem with border, regenerating map```

I print out `dom` and check the variables of `n_obs` and `add_border_res`, found out that `dom` is always 1, and `add_border_res` makes `n_obs == 0 || add_border_res` true.

Could you please help on this? Thanks!

**Comment by avivt** [comment]
Hi Xu,
Let me look into it once I get back from Barcelona. I'll get back to you in
a couple of days.
Excited that you're using our code!

Best,
Aviv

**Comment by zhongwen** [comment]
Just a friendly ping. :)

**Comment by zhongwen** [comment]
Or, you may just put the data files somewhere, your homepage or Dropbox or something else, so that I can download the data files and play with.

**Comment by avivt** [comment]
Generating the data should work now. Instead of running script_make_data.m, you can have a look at scripts/make_data_gridworld_nips.m. 
Also, I uploaded some sample data files in the data folder.
Let me know if you run into additional issues.

**Comment by zhongwen** [comment]
Hi Aviv, Thanks for your prompt reply! I just tried the current version of your code. After solving some issues on paths, and remove `set_var` to make it run in MATLAB 2016 (actually I did not find `set_var` in MATLAB 2015 either), I can run `scripts/make_data_gridworld_nips.m` now. See [here](https://github.com/zhongwen/VIN/commit/e114fde14755cef1fcbb21ee129c21c123ccf2d0) for my specific modifications.

However, I still have the issues I mentioned previously. The MATLAB program keeps showing 

`no obstacles added, or problem with border, regenerating map`

**Comment by avivt** [comment]
Hi Xu,
set_var.m is in the utils folder, if you run addpaths.m it should be added
to the path, and Matlab should find it. Are you sure your path is set
correctly?
I ran the script in scripts/make_data_gridworld_nips.m and it ran fine. Can
you try setting up your path and running it?

Best,
Aviv

**Comment by zhongwen** [comment]
Hi Aviv,

Here is what I met the path issue:
```
>> make_data_gridworld_nips
Undefined function or variable 'obstacle_gen'.

Error in script_make_data (line 56)
    obs = obstacle_gen(dom_size,goal,maxObsSize);

Error in make_data_gridworld_nips (line 19)
script_make_data;
```

And here is the output of ```path``` command:

```
>> path

		MATLABPATH

	util
	ObstacleGenerators
	MDPs
	./matlab_bgl
	./matlab_bgl/custom
	./matlab_bgl/doc
	./matlab_bgl/doc/html
	./matlab_bgl/doc/html/core_numbers_example
	./matlab_bgl/doc/html/images
	./matlab_bgl/doc/html/new_in_3
	./matlab_bgl/doc/html/new_in_4
	./matlab_bgl/doc/html/planar_graphs
	./matlab_bgl/doc/html/record_alg
	./matlab_bgl/doc/html/red_black
	./matlab_bgl/doc/html/reweighted_graphs
	./matlab_bgl/examples
	./matlab_bgl/graphs
	./matlab_bgl/libmbgl
	./matlab_bgl/libmbgl/include
	./matlab_bgl/libmbgl/libmbgl_test
	./matlab_bgl/libmbgl/yasmic
	./matlab_bgl/libmbgl/yasmic/boost_mod
	./matlab_bgl/libmbgl/yasmic/util
	./matlab_bgl/test
	/Users/zhongwen/Codes/theano_VIN/scripts
        ..
	.......... (many more for the MATLAB toolboxes)
```

After adding some paths, I can run the script but it shows 
`no obstacles added, or problem with border, regenerating map`.

It seems that the script cannot produce valid maps.

=================
My plan is to take the data you have produced and reimplement your VIN algorithm in TensorFlow. So, if this issue cannot be reproduced on your side, just ignore it. It's enough for me to have the data. :)

**Comment by avivt** [comment]
weird that it doesn't find obstacle_gen even though ObstacleGenerators in
in the path. Are you using Matlab 2015/2016?

Cool that you're implementing it in tensorflow! I'll upload also the test
dataset I used (current one was used for training).

**Comment by zhongwen** [comment]
It's MATLAB 2016a. Thanks for the help on the data!
