### ISSUE TITLE
Difficulties in reproducing results from the paper

### ISSUE THREAD

**Issue by itdxer** [avivt/VIN#7]
I've encountered some issues in reproducing results from the VIN paper. I've run commands from the [scripts/nips_gridworld_experiments_VIN.sh](https://github.com/avivt/VIN/blob/master/scripts/nips_gridworld_experiments_VIN.sh) file, but I was able to reproduce only results for the 8x8 grid world. I've trained 6 times network for 16x16 grid world problem, but the best results that I've gotten was with loss 0.1006 and accuracy: 95.7% (loss 0.11 and accuracy 95% on average). In addition, I've trained network for 28x28 grid world problem, but my loss after 120 epochs was 0.26 and accuracy 89.37%.

Is there anything that I can do to get the same (or similar) accuracy as in the paper?

**Comment by avivt** [comment]
Let me look into that - perhaps something broke down when I refactored the code.

**Comment by itdxer** [comment]
Great, thank you!

**Comment by itdxer** [comment]
One thing that I've noticed that not all invalid predictions are incorrect. For instance, instead of applying two steps east and east network can go north-east and then south east, or south-east and north-east. In all three cases trajectory has the same number of steps and reaches the same goal. It means that there are multiple optimal paths between two points and even though predicted action is different the overall trajectory is perfect. 

![](https://monosnap.com/image/5JnDsgTimA5rIjoSYnk2nFsDNL2fDI.png)

**Comment by avivt** [comment]
Hi Yurii,

So I think there's some confusion with the loss and error terminology.

Let's look at the 16x16 case:

In the paper we report three success measures:

1. Prediction loss - this is (1 - the prediction accuracy), so, in this
case 1-0.95 = 0.05, which is what we report in the paper. So the results
you got (and which I got as well) agree.

2. Success rate - this is the success rate of rolling out the policy for a
whole trajectory, and seeing whether it reaches the goal or not. This rate
is not calculated in the python code, but I have a different Matlab script
<https://github.com/avivt/VIN/blob/master/test_network.m> for measuring it,
and this should give the 99.3% success reported in the paper. As you
noticed yourself, even though the VIN's action prediction accuracy is only
95%, it does a very good job at actually getting to the goal. This is the
point of using VINs :)

3. Trajectory difference - this is the average difference in length of the
successful trajectories and the shortest path. This is also calculated in
the Matlab script <https://github.com/avivt/VIN/blob/master/test_network.m>.

I'm not sure what is the 0.11 loss that you report, but if you are
referring to the NLL term in the python code, this is negative
log-likelihood, and we didn't report that in the paper.

Aviv

**Comment by itdxer** [comment]
That makes a lot more sense. Thank you for your answer!
